# Generated by Django 3.1.7 on 2021-03-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210322_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
