# Generated by Django 3.1.7 on 2021-03-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='is_mvp',
        ),
    ]
